schemaVersion: 2.2.0
metadata:
  name: aap-rosa-deploy-ansible
components:
  - name: developer-tools
    container:
      image: 'registry.redhat.io/devspaces/udi-rhel8:latest'
      memoryLimit: 1G
      mountSources: true
      sourceMapping: /projects
  - name: ansible-tools
    container:
      image: quay.io/ahussey/aap-rosa-ee:latest
      memoryRequest: 256M
      memoryLimit: 6Gi
      cpuRequest: 250m
      cpuLimit: 2000m
      sourceMapping: /projects
      args:
        - sleep
        - infinity
