# This playbook will be used by Ansible Automation Platform to deploy a `spoke` ROSA instance
- name: Run preflight checks
  ansible.builtin.import_playbook: rh.rosa.preflight

- name: Deploy a hub ROSA instance
  hosts: localhost
  connection: local
  become: false
  gather_facts: false
  tasks:
    - name: Deploy ROSA
      ansible.builtin.import_role:
        name: rh.rosa.create
    # - name: Bootstrap Hub
    #   ansible.builtin.import_role:
    #     name: rh.rosa.bootstrap_hub
    # - name: Conduct Day1 Ops
    #   ansible.builtin.import_role:
    #     name: rh.rosa.day1
    # - name: Conduct Day2 Ops
    #   ansible.builtin.import_role:
    #     name: rh.rosa.day2
