---
- name: Handle DNS verification failure
  hosts: localhost
  become: false
  gather_facts: false
  tasks:
    - name: Wait for DNS verification to succeed
      ansible.builtin.shell:
        cmd: |
          export AWS_DEFAULT_PROFILE=rosa_{{ rosa_cluster_name }}
          aws ec2 describe-vpc-endpoint-services | jq -r '.[][] | select(.Tags[].Value == "{{ rosa_cluster_name }}") | .PrivateDnsNameVerificationState' 2>/dev/null"
      register: dns_verification_result
      retries: 60
      delay: 10
      until: "'verified' in dns_verification_result.stdout_lines"